# Generated by Django 3.0.2 on 2020-01-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_app', '0002_auto_20200129_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='video',
            field=models.FileField(default=True, upload_to='video/'),
        ),
    ]
