# Generated by Django 3.0.2 on 2020-01-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_app', '0003_userprofile_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='video',
        ),
    ]
